### PR TITLE
[bugfix] Fix a (rare) bug in the hashmap merge logic causing inconsistent output in certain situations

### LINKED ISSUE #390: Inconsistent results when using (certain) conditions
It seems that some conditions can be crafted that will trigger non-reproducible behavior on the result side of `goquery`:
```
goquery -n 20 -i ethZ -f "2025-07-21 08:40" -l "2025-07-21 08:46" -c "dip = XX.YYY.61.199 or dip = XX.YYY.61.203 or dip = XX.YYY.61.197 or dip = XX.YYY.61.205 or dip = XX.YYY.61.195 or dip = XX.YYY.61.201" sip,dip,dport  -n 95
```
**Note:** `XX` and `YYY` were two- and three-digit IP octets (same, respectively) sanitized here. Also note the duplication of the `-n` parameter (unclear if that's relevant).

The above query produced seemingly random outputs each time called.

### PR DESCRIPTION
**Pull request by fako1024**
Closes #390

### CODE REVIEW

File: pkg/goDB/engine/query_linux.go [hunk 1]
```diff
@@ -26,7 +26,6 @@ type QueryRunner struct {
 
 	keepAlive      time.Duration
 	sem            concurrency.Semaphore
-	stats          *workload.Stats
```
Comment (fako1024) [inline pkg/goDB/engine/query_linux.go:29]: Drive-by (Linter complaining about unused field)

**Review by els0r — APPROVED** [review]
