### PR TITLE
[bugfix] Fix nil-pointer exception in config validation

### LINKED ISSUE #132: Config handling causes panic
The way the configuration is currently handled / validated can in at least one case cause a panic (run against current `develop`):
```
panic: value method github.com/els0r/goProbe/cmd/goProbe/config.APIConfig.validate called using nil *APIConfig pointer

goroutine 1 [running]:
github.com/els0r/goProbe/cmd/goProbe/config.(*APIConfig).validate(0x91a280?)
	<autogenerated>:1 +0x9d
github.com/els0r/goProbe/cmd/goProbe/config.(*Config).Validate(0xc000098100)
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/config/config.go:236 +0x130
github.com/els0r/goProbe/cmd/goProbe/config.Parse({0xa32ac0, 0xc0000140e0})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/config/config.go:275 +0x239
github.com/els0r/goProbe/cmd/goProbe/config.ParseFile({0x7ffd277c6570?, 0x188?})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/config/config.go:254 +0xa8
main.main()
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/goProbe.go:55 +0x12f
```

-> I didn't have an `api` subconfig set. Aside from the fact that this should be valid (because I didn't want to enable the API) it should definitively not panic.

DoD

- [x] Cross-check all existing config parameters for consistent handling of invalid input
- [x] Ensure optional config fields / objects can be omitted
- [x] Add / extend tests to ensure correct handling

### PR DESCRIPTION
**Pull request by els0r**
The changes in this PR also:

* simplify the way that the config is tested, separating validation tests from parsing tests
* removes the discovery config as that concept is currently unused and will be restructured anyhow

Closes #132

### CODE REVIEW

File: cmd/goProbe/config/config.go [hunk 1]
```diff
@@ -85,19 +85,10 @@ type LogConfig struct {
...
 type APIConfig struct {
-	Addr      string           `json:"addr" yaml:"addr"`
-	Metrics   bool             `json:"metrics" yaml:"metrics"`
-	Timeout   int              `json:"request_timeout" yaml:"request_timeout"`
-	Keys      []string         `json:"keys" yaml:"keys"`
-	Discovery *DiscoveryConfig `json:"service_discovery,omitempty" yaml:"service_discovery,omitempty"`
-}
-
-// DiscoveryConfig stores access parameters in case goProbe should publish it's API configuration so other services can discover it
-type DiscoveryConfig struct {
```
Comment (fako1024) [inline cmd/goProbe/config/config.go:96]: Ah neato, cleanup time! :muscle:

**Review by fako1024 — APPROVED** [review]
LGTM! Thanks for the quick fix and cleanup. I'll give it another whirl once merged!
