### PR TITLE
[bugfix] Print table footer on console even if no data was found

### LINKED ISSUE #360: Show table footer in goQuery even if no data was found
Currently, if a distributed query returns empty, only the following message is shown:
```
Status "missing_data": no data available for the specified interface(s) / time range (maybe goProbe was not running)
```
However, even without results it might be helpful to show the _footer_, in particular the trace ID in order to still be able to figure out what went wrong (in particular for cases where an empty result wasn't expected).

~Same argument for failed queries:~
```
Error running query: failed to execute query

      Error: Post "https://global-query-cli.dev.osdp.open.ch/_query": context canceled
  Statement:

        query: sip,dip,dport,proto,host
       ifaces: [any]

         from: Thu Jan 16 06:43:11 2025
           to: Fri Jan 17 06:43:11 2025

        limit: 15
```

### PR DESCRIPTION
**Pull request by fako1024**
Instead of breaking out of the table processing if no data was found the table will now still be printed, but the rows and their headers are simply omitted if no rows were received, leading to a footer-only output:
```
└─ $ ▶ ./goQuery   -d /home/fako/Downloads/db -f -1d -n 10 -i any sip,dip
Status "missing_data": no data available for the specified interface(s) / time range (maybe goProbe was not running)

Timespan    : [2025-04-25 11:31:49, 2025-04-26 11:31:49] (1d0s)
Interface   : 23 queried
Sorted by   : accumulated data volume (sent and received)
Query stats : displayed top 0 hits out of 0 in 2ms
```

Side-note: At some point we should refactor the whole printer concept, it's a bit contrived (also has several fundamental code issues caught by today's linter configs).

Closes #360

### CODE REVIEW

File: cmd/goQuery/cmd/root.go [hunk 1]
```diff
@@ -458,7 +458,6 @@ func entrypoint(cmd *cobra.Command, args []string) (err error) {
 			return err
 		}
 		logger.Infof("Status %q: %s", result.Status.Code, result.Status.Message)
-		return nil
```
Comment (fako1024) [inline cmd/goQuery/cmd/root.go:461]: This is the actual "fix" / trick: Just don't abort, both when querying locally or globally we continue to print.

File: pkg/goDB/engine/query.go [hunk 2]
```diff
@@ -268,15 +268,18 @@ func (qr *QueryRunner) RunStatement(ctx context.Context, stmt *query.Statement,
...
-	tSpanFirst, tSpanLast := time.Now().AddDate(100, 0, 0), time.Time{} // a hundred years in the future, the beginning of time
-	for _, workManager := range workManagers {
-		t0, t1 := workManager.GetCoveredTimeInterval()
-		if t0.Before(tSpanFirst) {
-			tSpanFirst = t0
-		}
-		if tSpanLast.Before(t1) {
-			tSpanLast = t1
+	// the covered time period is the union of all covered times (initialize to query time period in case no work managers are created
+	tSpanFirst, tSpanLast := time.Unix(stmt.First, 0), time.Unix(stmt.Last, 0)
```
Comment (fako1024) [inline pkg/goDB/engine/query.go:272]: Drive-by bugfix: If no data is found the time range is actually `[2125-04-26 11:12:24, 0001-01-01 00:00:00]`, we just didn't notice because we didn't print it...

**Review by els0r — APPROVED** [review]
