### PR TITLE
[bugfix][feature] Fix E2E test components for Prometheus metrics and improve packet / parsing issue counters

### LINKED ISSUE #296: Fix packet counters and track fragmented packets as parsing issues
It turns out that the current way of counting processed packets isn't perfectly in line with what a user would expect (probably a side effect of the recent performance enhancements in #284 . Unfortunately the E2E tests for Prometheus counters were silently broken so we didn't see that. :sweat: 

Since this will touch the metrics anyway: The idea for the additional metric would be to add a new packet parsing "error" / issue (similar to the existing one for truncated packets) to help spot issues simply by looking at the interface processing stats.

DoD

- [x] Fix E2E tests for Prometheus counters (and add protection against silent breakage in the future)
- [x] Extend metrics for packet parsing issues to track packet fragments

### PR DESCRIPTION
**Pull request by fako1024**
Closes #296

### CODE REVIEW

**Review by els0r — APPROVED** [review]

File: pkg/capture/capture.go [hunk 1]
```diff
@@ -292,17 +292,35 @@ func (c *Capture) process() <-chan error {
...
 				epHash, direction, errno := ParsePacketV4(ipLayer)
+
+				// Check for issues / errors during parsing (checked inline to avoid unnecessary function
+				// call to ParsePacket...())
+				if errno > capturetypes.ErrnoOK {
+					c.updateParsingErrorCounters(errno)
+					continue
+				}
+
+				c.stats.Processed++
```
Comment (els0r) [inline pkg/capture/capture.go:308]: As discussed: it feels obvious to put this on top before the processing.

A comment why it isn't in this particular case would be helpful.
