### PR TITLE
[bugfix][feature] Refactor of CaptureManager and capture logic

### LINKED ISSUE #117: Several race conditions in CaptureManager
After straightening out a couple of issues found in #88 via https://github.com/fako1024/slimcap/issues/33 running the E2E test on a basic flow (single interface, data being piped through a mock ring buffer source from a pcap file) revealed several data races, all of which seem to be related to the `CaptureManager` (respectively the state machine of the individual captures). The following ones I have found:

- [ ] Capture process is still running when `Free()` is called
Way back I think we had a quick chat about whether it's ensured that the capture is actually stopped when `closing()` is run. According to the test this doesn't seem to be the case:
```
WARNING: DATA RACE
Write at 0x00c0000d4940 by goroutine 13:
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).Free()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring_mock.go:329 +0x52
  github.com/els0r/goProbe/pkg/capture.closing()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:409 +0xa3
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:324 +0xc9

Previous read at 0x00c0000d4940 by goroutine 23:
  github.com/fako1024/slimcap/capture/afpacket/afring.(*Source).nextPacket()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring.go:331 +0x5e
  github.com/fako1024/slimcap/capture/afpacket/afring.(*Source).NextPacket()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring.go:136 +0x57
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).NextPacket()
      <autogenerated>:1 +0x6e
  github.com/els0r/goProbe/pkg/capture.(*Capture).capturePacket()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:446 +0x99
  github.com/els0r/goProbe/pkg/capture.(*Capture).process()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:514 +0x125
  github.com/els0r/goProbe/pkg/capture.capturing.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:352 +0x39

Goroutine 13 (running) created at:
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:315 +0x8e
  github.com/els0r/goProbe/pkg/capture.(*Manager).enable()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:108 +0x464
  github.com/els0r/goProbe/pkg/capture.(*Manager).Update.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:210 +0x3e
  github.com/els0r/goProbe/pkg/capture.(*RunGroup).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/rungroup.go:26 +0x73

Goroutine 23 (running) created at:
  github.com/els0r/goProbe/pkg/capture.capturing()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:352 +0x15b
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:324 +0xc9
``` 

- [ ] Access to flow map length while still running
It seems that `process()` is still adding packets to the initial map while `rotate()` checks if there are any flows present at all (this is probably the easiest thing to fix because it seems to me that this pre-check is simply not guarded by the current rotation copy-on-write magic):
```
WARNING: DATA RACE
Read at 0x00c000200db0 by goroutine 13:
  github.com/els0r/goProbe/pkg/capture.(*FlowLog).Len()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/flow_log.go:55 +0xc4
  github.com/els0r/goProbe/pkg/capture.(*Capture).rotate()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:534 +0x74
  github.com/els0r/goProbe/pkg/capture.captureCommandRotate.execute()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:203 +0x31
  github.com/els0r/goProbe/pkg/capture.capturing()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:365 +0x2e2
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:324 +0xc9

Previous write at 0x00c000200db0 by goroutine 23:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:203 +0x0
  github.com/els0r/goProbe/pkg/capture.(*FlowLog).Add()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/flow_log.go:115 +0x16b
  github.com/els0r/goProbe/pkg/capture.(*Capture).capturePacket()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:461 +0x40e
  github.com/els0r/goProbe/pkg/capture.(*Capture).process()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:514 +0x125
  github.com/els0r/goProbe/pkg/capture.capturing.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:352 +0x39

Goroutine 13 (running) created at:
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:315 +0x8e
  github.com/els0r/goProbe/pkg/capture.(*Manager).enable()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:108 +0x464
  github.com/els0r/goProbe/pkg/capture.(*Manager).Update.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:210 +0x3e
  github.com/els0r/goProbe/pkg/capture.(*RunGroup).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/rungroup.go:26 +0x73

Goroutine 23 (running) created at:
  github.com/els0r/goProbe/pkg/capture.capturing()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:352 +0x15b
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:324 +0xc9
```

- [ ] Writeout handler still processing after / during `Close()`
The writeout handler seems to still be attempting to perform its routines while / after the channel is being closed. Probably also not too tricky (I think I saw some random errors regarding sending on closed channel, maybe that's related):
```
WARNING: DATA RACE
Write at 0x00c000100070 by goroutine 8:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:357 +0x0
  github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).Close()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goprobe/writeout/handler.go:57 +0x6e4
  github.com/els0r/goProbe/pkg/e2etest.runGoProbe()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:231 +0x6c5
  github.com/els0r/goProbe/pkg/e2etest.testE2E()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:162 +0x429
  github.com/els0r/goProbe/pkg/e2etest.TestE2EBasic()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:57 +0x165
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1629 +0x47

Previous read at 0x00c000100070 by goroutine 16:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:160 +0x0
  github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).FullWriteout()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goprobe/writeout/handler.go:97 +0x2e5
  github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).HandleRotations.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goprobe/writeout/handler.go:160 +0x393

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1576 +0x216
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1906 +0xb44
  github.com/els0r/goProbe/pkg/e2etest.TestMain()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:522 +0x12e
  main.main()
      _testmain.go:59 +0x324

Goroutine 16 (running) created at:
  github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).HandleRotations()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goprobe/writeout/handler.go:133 +0xfa
  github.com/els0r/goProbe/pkg/e2etest.runGoProbe()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:225 +0x6a7
  github.com/els0r/goProbe/pkg/e2etest.testE2E()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:162 +0x429
  github.com/els0r/goProbe/pkg/e2etest.TestE2EBasic()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:57 +0x165
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1629 +0x47
```

- [ ] Access to packet stats while capture is running
There is a race when accessing the (mock) stats in `rotate()` because packets are being processed (and hence the counter is accessed) at the same time. This is arguably more of a problem in the slimcap mock source (I'll address that one in a separate issue, I guess an atomic counter won't add too much overhead) but I'm still raising it here because it might hint at an issue with the state machine:
```
WARNING: DATA RACE
Read at 0x00c0000962d8 by goroutine 21:
  github.com/fako1024/slimcap/capture/afpacket/socket.(*MockFileDescriptor).IncrementPacketCount()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/socket/socket_mock.go:48 +0xa9b
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).addPacket()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring_mock.go:159 +0xa69
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).addPacket-fm()
      <autogenerated>:1 +0x84
  github.com/fako1024/slimcap/capture/pcap.(*Source).NextPacketFn()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/pcap/pcap.go:150 +0xd4
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).AddPacketFromSource()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring_mock.go:110 +0xc5
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).Pipe.func1()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring_mock.go:193 +0xd6
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).Pipe.func2()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring_mock.go:204 +0x47

Previous write at 0x00c0000962d8 by goroutine 13:
  github.com/fako1024/slimcap/capture/afpacket/socket.(*MockFileDescriptor).GetSocketStats()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/socket/socket_mock.go:59 +0x104
  github.com/fako1024/slimcap/event.(*Handler).GetSocketStats()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/event/poll.go:81 +0x4f
  github.com/fako1024/slimcap/capture/afpacket/afring.(*Source).Stats()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring.go:268 +0xce
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).Stats()
      <autogenerated>:1 +0x51
  github.com/els0r/goProbe/pkg/capture.(*Capture).tryGetCaptureStats()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:590 +0xc4
  github.com/els0r/goProbe/pkg/capture.(*Capture).rotate()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:556 +0x351
  github.com/els0r/goProbe/pkg/capture.captureCommandRotate.execute()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:203 +0x31
  github.com/els0r/goProbe/pkg/capture.capturing()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:365 +0x2e2
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:324 +0xc9

Goroutine 21 (running) created at:
  github.com/fako1024/slimcap/capture/afpacket/afring.(*MockSource).Pipe()
      /home/fako/Develop/go/src/github.com/fako1024/slimcap/capture/afpacket/afring/afring_mock.go:191 +0x19e
  github.com/els0r/goProbe/pkg/e2etest.newPcapSource.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:393 +0x754
  github.com/els0r/goProbe/pkg/e2etest.setupSources.func1.1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/e2etest/e2e_test.go:290 +0x93
  github.com/els0r/goProbe/pkg/capture.initializing()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:337 +0xcd
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:324 +0xc9

Goroutine 13 (running) created at:
  github.com/els0r/goProbe/pkg/capture.(*Capture).Run()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:315 +0x8e
  github.com/els0r/goProbe/pkg/capture.(*Manager).enable()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:108 +0x464
  github.com/els0r/goProbe/pkg/capture.(*Manager).Update.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:210 +0x3e
  github.com/els0r/goProbe/pkg/capture.(*RunGroup).Run.func1()
      /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/rungroup.go:26 +0x73
```

@els0r TBH I'm not sure if that's all of them, but I think we'll have to urgently take a look at them (they are not cosmetic, the E2E test randomly fails even without race detection turned on, and since they are not solely related to the mock sources I'm pretty sure we might see weird issues in the wild at some point)... Maybe something we can discuss in a call as well?

### PR DESCRIPTION
**Pull request by fako1024**
Provides replacement for state machine logic with more simplistic approach. See inline comments for some pointers.

Closes #117

### CODE REVIEW

File: pkg/capture/capture.go [hunk 1]
```diff
@@ -43,172 +33,80 @@ var defaultSourceInitFn = func(c *Capture) (capture.Source, error) {
...
-		errs[i] = fmt.Sprintf("%s (%d)", err, count)
-		i++
-	}
-	sort.Slice(errs, func(i, j int) bool {
-		return errs[i] < errs[j]
-	})
-	return strings.Join(errs, "; ")
+// Captures denotes a named set of Capture instances, wrapping a map and the
+// required synchronization of all its actions
+type Captures struct {
```
Comment (fako1024) [inline pkg/capture/capture.go:42]: Created new type that wraps the cumbersome map[string]*Capture and provides convenience methods to handle all the locking without the caller having to worry about it.

File: pkg/capture/capture_manager.go [hunk 2]
```diff
@@ -1,436 +1,355 @@
...
-	captures     map[string]*ManagedCapture
-	ctx          context.Context
-	sourceInitFn sourceInitFn
-}
-
-type ManagedCapture struct {
-	capture *Capture
-	cancel  context.CancelFunc
-}
+	sync.RWMutex
```
Comment (fako1024) [inline pkg/capture/capture_manager.go:23]: This mutex is now solely responsible for locking the external methods (i.e. `Update()` / `Close()` (which under the hood is actually using `Update()` and access to the last rotation). Locking of the individual captures within the RunGroups is done by the new methods introduced for the `Captures` type.

File: pkg/capture/capture_manager.go [hunk 3]
```diff
@@ -1,436 +1,355 @@
...
+		"ifaces_removed", disable,
+	).Debug("updated interface configuration")
 }
 
-// ErrorsAll returns the error maps of all managed Capture instances.
-func (cm *Manager) ErrorsAll() map[string]ErrorMap {
-	errmapMutex := sync.Mutex{}
-	errormap := make(map[string]ErrorMap)
+// Close stops / closes all (or a set of) interfaces
+func (cm *Manager) Close(ctx context.Context, ifaces ...string) {
```
Comment (fako1024) [inline pkg/capture/capture_manager.go:274]: Solved the lock conundrum for `Update()` and `Close()` by using `Update()` to perform the close, not the other way around. That way, `Update()` (or rather `update()`) can govern the global lock, thus prohibiting concurrent calls to those methods.

File: pkg/capture/capture_manager.go [hunk 4]
```diff
@@ -1,436 +1,355 @@
...
+	cm.update(ctx, ifaces, enableIfaces, disableIfaces)
 }
 
-// ActiveFlows returns a copy of the current in-memory flow map. If iface is "all", flows for every interface are returned
-func (cm *Manager) ActiveFlows(ifaces ...string) map[string]capturetypes.FlowInfos {
-	ifaceFlows := make(map[string]*capturetypes.FlowLog)
-	ifaceFlowsMutex := sync.Mutex{}
+func (cm *Manager) update(ctx context.Context, ifaces config.Ifaces, enable, disable []string) {
 
-	cmCopy := cm.capturesCopy()
```
Comment (fako1024) [inline pkg/capture/capture_manager.go:309]: I completely removed the need to pull a full copy of the captures all the time. Instead, the new type `Captures` cleanly wraps all accesses to the map with barriers / locks where needed. Make this code much leaner and safer (because there's no need to worry about this anymore).

File: pkg/capture/capture.go (hunk 1 above)
Comment (els0r) [reply pkg/capture/capture.go:42]: Does it need to be public?

File: pkg/capture/capture_manager.go [hunk 5]
```diff
@@ -1,436 +1,355 @@
...
+				return
+			}
+
+			cm.captures.Delete(mc.iface)
+		})
 	}
+	rg.Wait()
 
-	return ifaceFlowInfos
+	logger.With("elapsed", time.Since(t0).Round(time.Millisecond).String()).Debug("updated interface list")
```
Comment (els0r) [inline pkg/capture/capture_manager.go:265]: This looks like a duplicate of line 266

File: pkg/capture/capture_test.go [hunk 6]
```diff
@@ -2,87 +2,299 @@ package capture
...
+
+func TestConcurrentMethodAccess(t *testing.T) {
+	for _, i := range []int{1, 2, 3, 10} {
+		t.Run(fmt.Sprintf("%d ifaces", i), func(t *testing.T) {
+			testConcurrentMethodAccess(t, i, 1000)
+		})
+	}
+}
+
+func testConcurrentMethodAccess(t *testing.T, nIfaces, nIterations int) {
```
[the remark this answers is not in the document]
Comment (els0r) [reply pkg/capture/capture_test.go:62]: And that a thousand times 😂 . This approach _really_ builds confidence that the manager is airtight.

File: pkg/capture/capturetypes/status.go [hunk 7]
```diff
@@ -1,51 +1,75 @@
...
-		return "capturing"
-	case StateClosing:
-		return "closing"
-	case StateError:
-		return "inError"
-	default:
-		return "unknown"
-	}
-}
+// State enumerates the activity states of a capture
```
Comment (els0r) [inline pkg/capture/capturetypes/status.go]: Just like with muscles in the body: if you don't use it, lose it.

File: pkg/goprobe/writeout/handler.go [hunk 8]
```diff
@@ -2,196 +2,97 @@ package writeout
...
-type Handler struct {
-	// LastRotation is the time the handler last rotated all flow maps
-	LastRotation time.Time
+type Handler interface {
+	HandleWriteout(ctx context.Context, timestamp time.Time, writeoutChan <-chan capturetypes.TaggedAggFlowMap) <-chan struct{}
+}
 
-	writeoutsChan  chan *writeout
-	captureManager *capture.Manager
+const WriteoutsChanDepth = 100
```
Comment (els0r) [inline pkg/goprobe/writeout/handler.go:19]: Is this one still used?

File: pkg/goprobe/writeout/handler.go [hunk 9]
```diff
@@ -2,196 +2,97 @@ package writeout
...
 
+type GoDBHandler struct {
```
Comment (els0r) [inline pkg/goprobe/writeout/handler.go:21]: I suggest that we put this into `godb.go` and leave the `handler.go` file lean as in: only defining the interface.

**Review by els0r — APPROVED** [review]
Good to go from my end. Minor comments:

- duplicate log line
- leaving the `writeout.Handler` interface def in its own file

File: pkg/capture/capture.go (hunk 1 above)
Comment (fako1024) [reply pkg/capture/capture.go:42]: Fair point - no, it doesn't. Will make it private then!

File: pkg/capture/capture_manager.go (hunk 5 above)
Comment (fako1024) [reply pkg/capture/capture_manager.go:265]: Whoopsie, good catch!

File: pkg/capture/capturetypes/status.go (hunk 7 above)
Comment (fako1024) [reply pkg/capture/capturetypes/status.go]: Already done while you were looking at the PR. Race condition, human-style :rofl:

File: pkg/goprobe/writeout/handler.go (hunk 8 above)
Comment (fako1024) [reply pkg/goprobe/writeout/handler.go:19]: Yep, in ` performWriteout()` of the `CaptureManager`. It's debatable of course where it belongs, but since it pertains to the _writeouts_ (not to the Manager) I'm inclined to leave it here.

File: pkg/goprobe/writeout/handler.go (hunk 9 above)
Comment (fako1024) [reply pkg/goprobe/writeout/handler.go:21]: Absolutely, done (and also added some comments and removed dead code).

File: pkg/goprobe/writeout/handler.go [hunk 10]
```diff
@@ -2,196 +2,97 @@ package writeout
...
 		}
-	}()
+
+		syslogWriter.Write(taggedMap.Map, taggedMap.Iface, timestamp.Unix())
+	}
 }
 
-func (h *Handler) HandleWriteouts() <-chan struct{} {
-	logger := logging.Logger()
+func (h *GoDBHandler) HandleWriteout(ctx context.Context, timestamp time.Time, writeoutChan <-chan capturetypes.TaggedAggFlowMap) <-chan struct{} {
```
[the remark this answers is not in the document]
Comment (fako1024) [reply pkg/goprobe/writeout/handler.go:89]: c.f. above, all done.

**Comment by fako1024** [comment]
> Good to go from my end. Minor comments:
> 
> * duplicate log line
> * leaving the `writeout.Handler` interface def in its own file

Nice, thanks for the quick feedback. Everything amended / done, will merge after successful test.

File: pkg/capture/capture_manager.go (hunk 3 above)
Comment (fako1024) [reply pkg/capture/capture_manager.go:273]: TY! :pray:
