### PR TITLE
[bugfix] Ensure that capture is stopped once a critical processing error occurs

### LINKED ISSUE #181: CaptureManager stalls after error was encountered on interface
On a PPPOE network interface that was brought down / up during the night (forcibly) the interruption caused the following error:
```
ts=2023-08-15T05:30:01.334+02:00 level=error msg="capture error: error polling for next packet: connection reset by peer (errno 104)" version=872abf81 iface=ppp0
ts=2023-08-15T05:35:00.131+02:00 level=info msg="rotation duration" version=872abf81 iface=eth1.10 rotation_duration=532.094µs
ts=2023-08-15T05:35:00.131+02:00 level=info msg="rotation duration" version=872abf81 iface=lo rotation_duration=504.843µs
^Cts=2023-08-15T09:35:18.394+02:00 level=info msg="shutting down gracefully" version=872abf81
ts=2023-08-15T09:35:18.397+02:00 level=info msg="rotation duration" version=872abf81 iface=eth1.10 rotation_duration=859.784µs
ts=2023-08-15T09:35:18.397+02:00 level=info msg="rotation duration" version=872abf81 iface=lo rotation_duration=1.427333ms
[chirp chirp]
```

That in itself is not an issue, but after that:

- no further rotations were performed
- a graceful shutdown got stuck (did not force-shutdown on its own)

A `kill -6` revealed the following stack trace: [stack.txt](https://github.com/els0r/goProbe/files/12342139/stack.txt)

### PR DESCRIPTION
**Pull request by fako1024**
~Not complete yet, so far only fixes teardown of an interface that encounters critical processing errors and avoids stalling of the CaptureManager on subsequent rotations. As a consequence, such interfaces are currently not brought up again automatically. It seems that we never refresh interfaces to match the configuration.~

Added teardown of interfaces that encounter critical processing errors and configuration manager that performs period config reloads (and also allows explicitly triggering a reload, should we want to pursue this via the API - so far it simply checks the config every 5 minutes and then calls the `Update()` method of the `CaptureManager` - also attempting to bring "back" any interfaces that have been torn down due to errors).

Closes #181

### CODE REVIEW

File: pkg/capture/capture.go [hunk 1]
```diff
@@ -167,11 +167,6 @@ func (c *Capture) run(ctx context.Context) (err error) {
 	// make sure to store when the capture started
 	c.startedAt = time.Now()
 
-	// Start up processing and error handling / logging in the
-	// background
-	go logErrors(ctx,
```
Comment (fako1024) [inline pkg/capture/capture.go:172]: See comments below.

File: pkg/capture/capture_manager.go [hunk 2]
```diff
@@ -360,11 +360,16 @@ func (cm *Manager) update(ctx context.Context, ifaces config.Ifaces, enable, dis
...
 			newCap := newCapture(iface, ifaces[iface]).SetSourceInitFn(cm.sourceInitFn)
-			if err := newCap.run(runCtx); err != nil {
+			if err := newCap.run(); err != nil {
 				logger.Errorf("failed to start capture: %s", err)
 				return
 			}
 
+			// Start up processing and error handling / logging in the
+			// background
+			go cm.logErrors(runCtx, iface,
```
Comment (fako1024) [inline pkg/capture/capture_manager.go:370]: I had to move tracking / logging to the `CaptureManager` (instead of handling the goroutine startup from the capture itself) because only this way can we manipulate the map of captures when processing has terminated prematurely (see below in `logErrors(...)` implementation).

File: pkg/capture/capture_manager.go [hunk 3]
```diff
@@ -454,6 +459,30 @@ func (cm *Manager) rotate(ctx context.Context, writeoutChan chan<- capturetypes.
 	).Debug("rotated interfaces")
 }
 
+func (cm *Manager) logErrors(ctx context.Context, iface string, errsChan <-chan error) {
+	logger := logging.FromContext(ctx)
+	for {
+		select {
```
Comment (fako1024) [inline pkg/capture/capture_manager.go:465]: If the capture was terminated in a "regular" fashion it should have happened via the context. Otherwise it has happened because of the error channel being closed from within `process()` first, which would indicate a critical error and trigger teardown of the interface.

File: pkg/capture/capture.go [hunk 4]
```diff
@@ -216,7 +211,10 @@ func (c *Capture) process() <-chan error {
 	c.wgProc.Add(1)
 	go func() {
 
-		defer c.wgProc.Done()
+		defer func() {
+			close(captureErrors)
```
Comment (fako1024) [inline pkg/capture/capture.go:215]: Added the `close()` statement (not only to track errors, but simply because we were missing that part of cleanup entirely so far, which would leave us with dead stuff after each interface teardown).

**Comment by fako1024** [comment]
Unfortunately this doesn't cut it. Contrary to my assumption the operation is racy and can lead to a double-attempt to close the capture :disappointed: (as seen in this CI run: https://github.com/els0r/goProbe/actions/runs/5865790755/job/15903367739)
```
2023/08/15 09:48:09 ERROR failed to close capture: cannot call Close() on nil / closed capture source iface=mock0
==================
WARNING: DATA RACE
Write at 0x00c0000a8488 by goroutine 446:
  github.com/els0r/goProbe/pkg/capture.(*Capture).close()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture.go:185 +0x77
  github.com/els0r/goProbe/pkg/capture.(*Manager).update.func1()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_manager.go:341 +0xda
  github.com/els0r/goProbe/pkg/capture.(*RunGroup).Run.func1()
      /home/runner/work/goProbe/goProbe/pkg/capture/rungroup.go:25 +0x39

Previous read at 0x00c0000a8488 by goroutine 236:
  github.com/els0r/goProbe/pkg/capture.(*Capture).close()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture.go:174 +0x3e
  github.com/els0r/goProbe/pkg/capture.(*Manager).logErrors()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_manager.go:474 +0x219
  github.com/els0r/goProbe/pkg/capture.(*Manager).update.func2.1()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_manager.go:370 +0x8b

Goroutine 446 (running) created at:
  github.com/els0r/goProbe/pkg/capture.(*RunGroup).Run()
      /home/runner/work/goProbe/goProbe/pkg/capture/rungroup.go:24 +0xe4
  github.com/els0r/goProbe/pkg/capture.(*Manager).update()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_manager.go:334 +0x3bd
  github.com/els0r/goProbe/pkg/capture.(*Manager).Close()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_manager.go:391 +0x13b
  github.com/els0r/goProbe/pkg/capture.testConcurrentMethodAccess()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_test.go:144 +0xb06
  github.com/els0r/goProbe/pkg/capture.TestConcurrentMethodAccess.func1()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_test.go:61 +0x4c
  testing.tRunner()
      /opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1629 +0x47

Goroutine 236 (running) created at:
  github.com/els0r/goProbe/pkg/capture.(*Manager).update.func2()
      /home/runner/work/goProbe/goProbe/pkg/capture/capture_manager.go:370 +0x7b9
  github.com/els0r/goProbe/pkg/capture.(*RunGroup).Run.func1()
      /home/runner/work/goProbe/goProbe/pkg/capture/rungroup.go:25 +0x39
==================
    testing.go:1446: race detected during execution of test
```

File: pkg/capture/capture_manager.go [hunk 5]
```diff
@@ -454,6 +458,35 @@ func (cm *Manager) rotate(ctx context.Context, writeoutChan chan<- capturetypes.
...
+		case <-ctx.Done():
+			return
+		case err, ok := <-errsChan:
+			if !ok {
+
+				// Ensure there is no conflict with calls to update() that might already be
+				// taking down this interface
+				cm.Lock()
```
Comment (fako1024) [inline pkg/capture/capture_manager.go:472]: This should avoid any conflicts with other methods that may be closing the capture.

**Comment by fako1024** [comment]
@els0r I think I tackled all issues here and found a rather elegant way to manager the configuration and hooking into the `CaptureManager`. I'll add a few comments to the code. Ready to review!

File: cmd/goProbe/config/monitor.go [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+	"sync"
+	"time"
+
+	"github.com/els0r/goProbe/pkg/logging"
+)
+
+const defaultReloadInterval = 5 * time.Minute
+
+// Monitor denotes a config monitor / manager
+type Monitor struct {
```
Comment (fako1024) [inline cmd/goProbe/config/monitor.go:15]: This one basically wraps the config path, loads it and allows both explicit and periodic reloading of the file. The config is stored in the manager (and can be retrieved via its `Config()` method) and is mutex-locked to avoid any races.
During a reload, a callback function can be provided (in this case the call to `CaptureManager.Update()`, which will cross-check for any changes in the config _AND_ attempt to restore the state present in that config, i.e. also bring up interfaces that were torn down before).

File: cmd/goProbe/goProbe.go [hunk 7]
```diff
@@ -52,11 +52,12 @@ func main() {
 	}
 
 	// Read / parse config file
-	config, err := gpconf.ParseFile(flags.CmdLine.Config)
+	configMonitor, err := gpconf.NewMonitor(flags.CmdLine.Config)
```
Comment (fako1024) [inline cmd/goProbe/goProbe.go:55]: As you can see, the required changes to the calling path are minimal (and from what I can see there are no side effects from this because the `config` variable is only used for the initial setup. After that, the only interaction / access to the config is via the `Reload()` / callback function of the monitor (hooking into the `CaptureManager`).

File: pkg/capture/capture_manager.go [hunk 8]
```diff
@@ -143,6 +143,7 @@ func (cm *Manager) ScheduleWriteouts(ctx context.Context, interval time.Duration
 			select {
 			case <-ctx.Done():
 				logger.Info("stopping rotation handler")
+				ticker.Stop()
```
Comment (fako1024) [inline pkg/capture/capture_manager.go:146]: Just making sure resources from the ticker are cleaned up, we forgot that.

**Comment by fako1024** [comment]
@els0r Alright, new POST route is in and config reload is refactored. As for the `gpctl` extension I might need your input though: Currently there is no subcommand for a config reload registered, there's just:
```
Get or update goProbe's runtime configuration

If the (list of) interface(s) is provided as an argument, it will only
show the configuration for them. Otherwise, all configurations are printed

The list of interfaces is ignored if --file is provided to reload
goprobe's runtime configuration
```
How would you like the new reload from disk functionality in there? If I just add another parameter like `-r` it of course breaks the whole explanation and conflicts with the existing command set. Or should I trigger on `... config reload` and extending the command to `config [IFACES]|reload`. Not super pretty either IMHO, but I don't have strong feelings about that, so let me know how you like it...

**Comment by els0r** [comment]
> @els0r Alright, new POST route is in and config reload is refactored. As for the `gpctl` extension I might need your input though: Currently there is no subcommand for a config reload registered, there's just:
> 
> ```
> Get or update goProbe's runtime configuration
> 
> If the (list of) interface(s) is provided as an argument, it will only
> show the configuration for them. Otherwise, all configurations are printed
> 
> The list of interfaces is ignored if --file is provided to reload
> goprobe's runtime configuration
> ```
> 
> How would you like the new reload from disk functionality in there? If I just add another parameter like `-r` it of course breaks the whole explanation and conflicts with the existing command set. Or should I trigger on `... config reload` and extending the command to `config [IFACES]|reload`. Not super pretty either IMHO, but I don't have strong feelings about that, so let me know how you like it...

Neat. Thanks for taking this into consideration as well. To keep things simple (in terms of shuffling around cobra boilerplate), I would go with a `--reload|-r` flag and adjust the explanation of the command.

Otherwise, you could consider moving the `[IFACES]` part underneath a `config list` command. But at this stage, I wouldn't spend too much time on it and go with a simple flag as stated above.

File: cmd/goProbe/config/monitor.go [hunk 9]
```diff
@@ -0,0 +1,129 @@
...
+	path   string
+	config *Config
+
+	reloadInterval time.Duration
+
+	sync.RWMutex
+}
+
+// CallbackFn denotes a function to be called upon successful reload of the configuration
+type CallbackFn func(context.Context, Ifaces) ([]string, []string, []string, error)
```
Comment (els0r) [inline cmd/goProbe/config/monitor.go:25]: Named return parameters could make clearer why the structure of the type is the way it is: to return `added`, `updated` and `deleted`.

File: cmd/goProbe/config/monitor.go [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+		if _, _, _, err = fn(ctx, config.Interfaces); err != nil {
+			return fmt.Errorf("failed to execute config reload callback function: %w", err)
+		}
+	}
+
+	m.Lock()
+	m.config = config
+	m.Unlock()
+
+	logging.FromContext(ctx).Debugf("config reloaded from %s", m.path)
```
Comment (els0r) [inline cmd/goProbe/config/monitor.go:104]: Structured logging

**Review by els0r — APPROVED** [review]
Thanks for adjusting the client already! Would be cool to see the `--reload` in `gpctl` as well.

Minor mini because of logging, but in any case good to go.

File: cmd/goProbe/config/monitor.go (hunk 9 above)
Comment (fako1024) [reply cmd/goProbe/config/monitor.go:25]: Yeah, had that initially, just removed it to make the definition shorter (because we don't actually care / use these parameters for the callback in the monitor, they just happen to be there :stuck_out_tongue:) - But I'm game either way and add them.

File: cmd/goProbe/config/monitor.go [hunk 11]
```diff
@@ -0,0 +1,129 @@
...
+	return nil
+}
+
+////////////////////////////////////////////////////////////////////////
+
+func (m *Monitor) reloadPeriodically(ctx context.Context, fn CallbackFn) {
+
+	logger := logging.FromContext(ctx)
+	ticker := time.NewTicker(m.reloadInterval)
+	logger.Infof("starting config monitor (interval: %v)", m.reloadInterval)
```
[the remark this answers is not in the document]
Comment (fako1024) [reply cmd/goProbe/config/monitor.go:115]: OKOK... :wink:
