### PR TITLE
[bugfix] Make sure that the interface selector is set on `args.Prepare()`

### LINKED ISSUE #288: The `iface` attribute is not added when more than one interface is selected
### Expected Behavior

When running an interface query with more than 1 interface `iface` should be added as an attribute.

### How to Reproduce

```
goquery -i eth40,eth42 -n 10 -f -5m dip

                    packets   packets             bytes      bytes
              dip        in       out      %         in        out      %
    98.147.19.204  674.51 k  855.74 k  92.67  116.94 MB  546.59 MB  74.66
      99.84.71.60    5.62 k   20.52 k   1.58  379.51 kB  161.93 MB  18.26
      20.245.3.79   16.09 k   29.38 k   2.75    4.01 MB   31.69 MB   4.02
  173.194.167.234  857.00      7.35 k   0.50   72.54 kB    9.03 MB   1.02
  213.156.239.107  599.00      1.53 k   0.13  119.67 kB    2.73 MB   0.32
   173.194.12.231  187.00      1.38 k   0.09   16.52 kB    1.69 MB   0.19
   142.251.33.102  159.00    760.00     0.06   19.54 kB  920.93 kB   0.10
      23.2.84.184  525.00    468.00     0.06   39.32 kB  891.08 kB   0.10
       10.14.99.2    4.13 k    0.00     0.25  637.13 kB    0.00  B   0.07
  142.251.215.226  269.00    511.00     0.05   45.34 kB  527.11 kB   0.06
                        ...       ...               ...        ...
                   719.34 k  931.98 k         125.95 MB  762.76 MB

          Totals:              1.65 M                    888.71 MB

Timespan / Interface : [2024-03-29 23:43:12, 2024-03-29 23:50:00] (7m0s) / eth40,eth42
```

### PR DESCRIPTION
**Pull request by els0r**
The side-effect before was that it wasn't set, leading to the interface attribute not being present in the output when >1 interfaces were part of a query.

Also:
* instrument each per-interface processing with a span

Closes #288

### CODE REVIEW

**Comment by els0r** [comment]
Tested functionality with
```
goquery -i mvpn0,eth0 -f -5m sip,dip,dport -n 25

                                                     packets   packets             bytes      bytes
    iface              sip              dip  dport        in       out      %         in        out      %
     eth0      10.236.2.56    10.236.130.23    443  466.00    650.00     5.03   48.88 kB  483.48 kB   1.84
     eth0      10.236.2.56    10.236.146.23    443  304.00    428.00     3.30   31.81 kB  316.60 kB   1.20
    mvpn0       44.0.105.8        44.9.2.92     22   33.00     23.00     0.25    1.75 kB    6.74 kB   0.03
    mvpn0       44.0.104.8        44.9.2.92     22   33.00     23.00     0.25    1.75 kB    6.74 kB   0.03
```

File: pkg/goDB/engine/query.go [hunk 1]
```diff
@@ -98,6 +96,8 @@ func (qr *QueryRunner) RunStatement(ctx context.Context, stmt *query.Statement)
 		return res, fmt.Errorf("failed to parse query type: %w", err)
 	}
 
+	// make sure that the interface label is added if a query contains
```
Comment (fako1024) [inline pkg/goDB/engine/query.go:99]: Incomplete / misplaced comment?

File: pkg/query/args.go [hunk 2]
```diff
@@ -404,10 +405,30 @@ func (a *Args) Prepare(writers ...io.Writer) (*Statement, error) {
 
 	}
 
+	// set and validate the interfaces
+	if a.Ifaces == "" {
+		err := newArgsError(
+			"iface",
+			invalidInterfaceMsg,
+			&types.ParseError{
+				Description: "empty input",
```
Comment (fako1024) [inline pkg/query/args.go:414]: Maybe this could be more specific (as in: "no interface name specified") to be more clear to the recipient and to be in line with the "invalid interface name" message (language-wise)?

**Review by fako1024 — APPROVED** [review]
Two small nitpicks, nice catch!
