### PR TITLE
[bugfix] OpenAPI Spec: fix duplicate route registration in query API

### LINKED ISSUE #345: Fix release v4.1.4
Pipeline step https://github.com/els0r/goProbe/actions/runs/10922138941 failed.

There's a problem with OpenAPI spec registration:

- [x] Write test for it so it fails faster (during testing stage)
- [x] Fix

### PR DESCRIPTION
**Pull request by els0r**
Makes sure that the `/_query` endpoint is not registered twice. This commit also adds a test to make sure any errors with API registration are caught during regular testing, not just the release stage.

Closes #345

### CODE REVIEW

File: pkg/api/globalquery/server/server_test.go [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+import (
+	"bytes"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestGenerateOpenAPISpec(t *testing.T) {
+	buf := &bytes.Buffer{}
+	s := New("localhost:8146", nil, nil)
```
Comment (fako1024) [inline pkg/api/globalquery/server/server_test.go:12]: Tests should IMHO try to avoid actually firing up servers wherever possible (there's no guarantee that a) you're allowed to do that on any node that runs these tests and b) the port is available, which can lead to weird / totally random failures). Can't you just use the underlying handlers directly or in memory without actually firing up the server?

File: pkg/api/server/server_test.go [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+import (
+	"bytes"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestGenerateOpenAPISpec(t *testing.T) {
+	buf := &bytes.Buffer{}
+	s := NewDefault("test", "localhost:8146")
```
Comment (fako1024) [inline pkg/api/server/server_test.go:12]: See above.

**Review by fako1024 — APPROVED** [review]
Approved so you're not blocked, but if at all possible it would be good to get rid of the server / port instantiation in the tests...

File: pkg/api/globalquery/server/server_test.go (hunk 1 above)
Comment (els0r) [reply pkg/api/globalquery/server/server_test.go:12]: Don't worry. The server isn't started up until you call `Start`.

File: pkg/api/server/server_test.go (hunk 2 above)
Comment (els0r) [reply pkg/api/server/server_test.go:12]: See above.
