### PR TITLE
[bugfix] Fix missing query route and DB path parsing in goQuery API

### LINKED ISSUE #340: goProbe query API missing "/_query" endpoint & broken config file handling
It seems that one of the recent changes (probably #309) introduced to regressions:

- The `goProbe` direct API doesn't provide a `/_query` endpoint anymore, only the validation ones. The distributed API has all three available (probably a copy/paste mishap)
- Even after restoring that, the query via API will always attempt to query the DB at the default location in `/usr/local/` (cause by a race condition in assignment of the DB path, which now happens _after_ the endpoints are registered)

### PR DESCRIPTION
**Pull request by fako1024**
See comments in PR code for details.

Closes #340

### CODE REVIEW

File: pkg/api/goprobe/server/server.go [hunk 1]
```diff
@@ -24,16 +23,10 @@ type Server struct {
...
 
-// SetDBPath sets the path to the database directory
-func (server *Server) SetDBPath(path string) *Server {
-	server.dbPath = path
-	return server
-}
-
 // New creates a new goprobe API server
-func New(addr string, captureManager *capture.Manager, configMonitor *config.Monitor, opts ...server.Option) *Server {
+func New(addr, dbPath string, captureManager *capture.Manager, configMonitor *config.Monitor, opts ...server.Option) *Server {
```
Comment (fako1024) [inline pkg/api/goprobe/server/server.go:27]: Made the path a required argument for the API as it is not optional and cannot be guessed properly (just because we fall back here to the default doesn't mean this has been done elsewhere in the same way).

File: pkg/api/query_api_ops.go [hunk 2]
```diff
@@ -14,6 +14,19 @@ var queryTags = []string{"Query"}
 
 // RegisterQueryAPI registers all query related endpoints
 func RegisterQueryAPI(a huma.API, caller string, querier query.Runner, middlewares huma.Middlewares) {
+	// query running
+	huma.Register(a,
```
Comment (fako1024) [inline pkg/api/query_api_ops.go:18]: This section exists below for the distributed query, but seems to have been forgotten here...

File: .gitignore [hunk 3]
```diff
@@ -14,7 +14,3 @@ go.work.sum
 .db/
 tmp/
 bin/
-goProbe
```
Comment (fako1024) [inline .gitignore:17]: These were triggering on the `cmd/XXX` subfolders, ignoring changes under them.

**Review by els0r — APPROVED** [review]
I totally dropped the ball on this one.

Thanks for the fix!
