### PR TITLE
[bugfix] Implement GPDir read / open path recovery method and refactor some parts of the code

### LINKED ISSUE #388: Latest data path may change while query is running
Due to the changes introduced in #50 the directory path (or rather: name) of the current day changes upon each writeout (so every 5 minutes by default). If a query runs while this is happening (either a long running query or simply out of coincidence) this may (rightfully) lead to a fatal error:
```
ts=2025-07-04T09:51:54.630+02:00 level=error msg="metadata file `/db/lacp20.84/2025/07/1751587200_hG73-0-0-WSALNw-OUBUsR-CPpP3-YdH23/.blockmeta` missing" version=devel worker.id=7 iface=lacp20.84
ts=2025-07-04T09:52:41.520+02:00 level=error msg="metadata file `/db/lacp60.3715/2025/07/1751587200_s0W9-0-0-aMnG2j7-yephyg8-GNfEr-JXbTo/.blockmeta` missing" version=devel worker.id=6 iface=lacp60.3715
ts=2025-07-04T09:53:23.045+02:00 level=error msg="metadata file `/db/lacp64.150/2025/07/1751587200_C929-ZM2-0-K1vfha7-0NwxXm7-0ZWbm-cj7Gq/.blockmeta` missing" version=devel worker.id=6 iface=lacp64.150
```

Options of mitigation (multiple may apply):

- [ ] Reverse order of processing (to read most recent data / directory _first_) -> reduces chance, but doesn't fully mitigate
- [ ] Read `.blockmeta` at exact time of `walkDB` run and store with workload (unclear if possible / opportunistic, but in theory we have to do it at some point anyway)
- [ ] Ensure that the _current_ directory is included in a non-mutating way (e.g. keep symlink to current one and exclude "real" directory from query) -> complicated, might still be racy...

### PR DESCRIPTION
**Pull request by fako1024**
Closes #388

### CODE REVIEW

File: pkg/goDB/storage/gpfile/gpdir.go [hunk 1]
```diff
@@ -190,19 +196,30 @@ func (d *GPDir) ReadBlockAtIndex(colIdx types.ColumnIndex, blockIdx int) ([]byte
 		return nil, ErrDirNotOpen
 	}
 
-	// Load column if required
-	_, err := d.Column(colIdx)
+	// Attempt to read the block
+	data, err := d.readBlockAtIndex(colIdx, blockIdx)
```
Comment (fako1024) [inline pkg/goDB/storage/gpfile/gpdir.go:200]: This will allow recovery even if the write-out happened _after_ the metadata has been read but _before_ a column / `GPFile` has been accessed / lazy-loaded.

**Review by els0r — APPROVED** [review]
