### PR TITLE
[bugfix] Move capture handler call Free() to end of closing state to avoid race condition

### LINKED ISSUE #97: Race condition in slimcap capture shutdown
There seems to be a (minor) race condition when calling `Close()` and `Free()` on a capture source on shutdown:
```
2023-04-05T14:18:45.888+0200  info    goProbe/goProbe.go:232  shutting down gracefully        {"app_name": "goProbe_alpine", "app_version": "872abf81"}
2023-04-05T14:18:45.889+0200    info    capture/capture.go:437  closing capture handle  {"app_name": "goProbe_alpine", "app_version": "872abf81", "iface": "lo", "state": "closing"}
2023-04-05T14:18:45.889+0200    info    capture/capture.go:437  closing capture handle  {"app_name": "goProbe_alpine", "app_version": "872abf81", "iface": "eth0", "state": "closing"}
2023-04-05T14:18:45.889+0200    error   capture/capture.go:534  failed to free capture resources: cannot call Free() on open capture source, call Close() first {"app_name": "goProbe_alpine", "app_version": "872abf81", "iface": "lo", "state": "capturing"}
2023-04-05T14:18:45.893+0200    info    writeout/handler.go:261 completed all writeouts {"app_name": "goProbe_alpine", "app_version": "872abf81"}
2023-04-05T14:18:45.893+0200    info    goProbe/goProbe.go:251  graceful shut down completed    {"app_name": "goProbe_alpine", "app_version": "872abf81"}
``` 

`Free()` is obviously (sometimes) called before `Close()` (which makes sense as there currently is no "termination" state machine / handling in the `process()` method.

DoD

- [x] Ensure that `Free()` is only called _after_ `Close()` has returned

### PR DESCRIPTION
**Pull request by fako1024**
Moves the call to `Free()` out of the processing routine (where it doesn't belong anyway) into the closing state handler.

Closes #97

### CODE REVIEW

File: pkg/capture/capture.go [hunk 1]
```diff
@@ -424,6 +424,12 @@ func closing(c *Capture) stateFn {
 	close(c.cmdChan)
 	c.closed = true
 
+	// free resources of the capture handle
+	if err := c.captureHandle.Free(); err != nil {
```
Comment (fako1024) [inline pkg/capture/capture.go:428]: @els0r Four-eyes principle: Is it correct to assume that the processing routine has finished at this point, or could it still be happening that `process()` is running? I doubt it (because at this point everything needs to have been rotated and hence left the blocking state) but I'm not 100% sure...

Comment (els0r) [reply pkg/capture/capture.go:428]: Pretty sure that's the case. Will provide more meaningful feedback once in front of proper screen.

Comment (els0r) [reply pkg/capture/capture.go:428]: It is the case, although not immediately visible: the only way to reach state `closing` is via the capture context being cancelled. That only happens _after_ the rotation has been completed (see line 240 and onwards in `main` function, or `Update` of the capture manager).

**Review by els0r — APPROVED** [review]

File: pkg/capture/capture.go (hunk 1 above)
Comment (fako1024) [reply pkg/capture/capture.go:428]: Excellent, thanks for cross-checking! :clap:
